# Generated by Django 5.2.5 on 2025-09-01 14:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('item', '0001_initial'),
        ('pre_job', '0010_quotation_not_approved_reason_remark_and_more'),
        ('series', '0001_initial'),
        ('team', '0002_technician'),
        ('unit', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dn_number', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('signed_delivery_note', models.FileField(blank=True, null=True, upload_to='delivery_notes/')),
                ('delivery_status', models.CharField(choices=[('Delivery Pending', 'Delivery Pending'), ('Delivered', 'Delivered')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('series', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='series.numberseries')),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryNoteItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('range', models.CharField(blank=True, max_length=100, null=True)),
                ('quantity', models.PositiveIntegerField(blank=True, null=True)),
                ('delivered_quantity', models.PositiveIntegerField(blank=True, null=True)),
                ('delivery_note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='job_execution.deliverynote')),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='item.item')),
                ('uom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='unit.unit')),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryNoteItemComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('component', models.CharField(max_length=100)),
                ('value', models.CharField(max_length=200)),
                ('delivery_note_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='job_execution.deliverynoteitem')),
            ],
        ),
        migrations.CreateModel(
            name='WorkOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wo_number', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('status', models.CharField(blank=True, choices=[('Processing', 'Processing'), ('Manager Approval', 'Manager Approval'), ('Approved', 'Approved'), ('Declined', 'Declined'), ('Delivered', 'Delivered'), ('Closed', 'Closed'), ('Submitted', 'Submitted')], default='Collection Pending', max_length=20, null=True)),
                ('date_received', models.DateField(blank=True, null=True)),
                ('expected_completion_date', models.DateField(blank=True, null=True)),
                ('onsite_or_lab', models.CharField(blank=True, choices=[('Onsite', 'Onsite'), ('Lab', 'Lab')], max_length=20, null=True)),
                ('site_location', models.TextField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('manager_approval_status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Declined', 'Declined')], default='Pending', max_length=20)),
                ('decline_reason', models.TextField(blank=True, null=True)),
                ('invoice_status', models.CharField(blank=True, choices=[('pending', 'pending'), ('Raised', 'Raised'), ('processed', 'processed')], default='pending', max_length=20, null=True)),
                ('due_in_days', models.IntegerField(blank=True, null=True)),
                ('received_date', models.DateField(blank=True, null=True)),
                ('wo_type', models.CharField(blank=True, choices=[('Single', 'Single'), ('Split', 'Split')], max_length=10, null=True)),
                ('application_status', models.CharField(blank=True, max_length=20, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_work_orders', to='team.technician')),
                ('purchase_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='work_orders', to='pre_job.purchaseorder')),
                ('quotation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='work_orders', to='pre_job.quotation')),
            ],
        ),
        migrations.AddField(
            model_name='deliverynote',
            name='work_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_notes', to='job_execution.workorder'),
        ),
        migrations.CreateModel(
            name='WorkOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(blank=True, null=True)),
                ('unit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('range', models.CharField(blank=True, max_length=100, null=True)),
                ('certificate_uut_label', models.CharField(blank=True, max_length=100, null=True)),
                ('certificate_number', models.CharField(blank=True, max_length=100, null=True)),
                ('calibration_date', models.DateField(blank=True, null=True)),
                ('calibration_due_date', models.DateField(blank=True, null=True)),
                ('uuc_serial_number', models.CharField(blank=True, max_length=100, null=True)),
                ('certificate_file', models.FileField(blank=True, null=True, upload_to='certificates/')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_order_items', to='team.technician')),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='item.item')),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='unit.unit')),
                ('work_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='job_execution.workorder')),
            ],
        ),
    ]
