# Generated by Django 5.2.5 on 2025-09-01 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_execution', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorder',
            name='invoice_file',
            field=models.FileField(blank=True, null=True, upload_to='invoices/'),
        ),
    ]
