# Generated by Django 5.2.5 on 2025-09-01 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_execution', '0002_workorder_invoice_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorder',
            name='payment_reference_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
