# Generated by Django 5.2.4 on 2025-07-31 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_execution', '0002_alter_workorder_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workorder',
            name='status',
            field=models.CharField(choices=[('Collection Pending', 'Collection Pending'), ('Collected', 'Collected'), ('Processing', 'Processing'), ('Manager Approval', 'Manager Approval'), ('Approved', 'Approved'), ('Declined', 'Declined'), ('Delivered', 'Delivered'), ('Closed', 'Closed')], default='Collection Pending', max_length=20),
        ),
    ]
