# Generated by Django 5.2.5 on 2025-09-18 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_execution', '0003_workorder_payment_reference_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workorder',
            name='invoice_status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('raised', 'Raised'), ('processed', 'Processed')], default='pending', max_length=20, null=True),
        ),
    ]
