# Generated by Django 5.2.4 on 2025-07-31 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_execution', '0004_alter_workorder_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workorder',
            name='status',
            field=models.CharField(blank=True, choices=[('Processing', 'Processing'), ('Manager Approval', 'Manager Approval'), ('Approved', 'Approved'), ('Declined', 'Declined'), ('Delivered', 'Delivered'), ('Closed', 'Closed')], default='Collection Pending', max_length=20, null=True),
        ),
    ]
