# Generated by Django 5.2.5 on 2025-09-25 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_execution', '0004_alter_workorder_invoice_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deliverynote',
            options={'ordering': ['-created_at'], 'verbose_name': 'Delivery Note', 'verbose_name_plural': 'Delivery Notes'},
        ),
        migrations.AddField(
            model_name='deliverynote',
            name='due_in_days',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deliverynote',
            name='invoice_file',
            field=models.FileField(blank=True, null=True, upload_to='invoices/'),
        ),
        migrations.AddField(
            model_name='deliverynote',
            name='invoice_status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('raised', 'Raised'), ('processed', 'Processed')], default='pending', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='deliverynote',
            name='received_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='deliverynote',
            name='delivery_status',
            field=models.CharField(choices=[('Delivery Pending', 'Delivery Pending'), ('Delivered', 'Delivered')], default='Delivery Pending', max_length=20),
        ),
    ]
