# Generated by Django 5.2.5 on 2025-09-25 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_execution', '0005_alter_deliverynote_options_deliverynote_due_in_days_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deliverynote',
            options={},
        ),
        migrations.RemoveField(
            model_name='deliverynote',
            name='due_in_days',
        ),
        migrations.RemoveField(
            model_name='deliverynote',
            name='invoice_file',
        ),
        migrations.RemoveField(
            model_name='deliverynote',
            name='invoice_status',
        ),
        migrations.RemoveField(
            model_name='deliverynote',
            name='received_date',
        ),
        migrations.AlterField(
            model_name='deliverynote',
            name='delivery_status',
            field=models.CharField(choices=[('Delivery Pending', 'Delivery Pending'), ('Delivered', 'Delivered')], max_length=20),
        ),
    ]
