# Generated by Django 5.2.5 on 2025-09-25 18:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_execution', '0006_alter_deliverynote_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorder',
            name='invoice_delivery_note',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice_work_orders', to='job_execution.deliverynote'),
        ),
    ]
