# Generated by Django 5.2.4 on 2025-08-01 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_execution', '0006_alter_workorder_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workorder',
            name='created_by',
        ),
    ]
