# Generated by Django 5.2.5 on 2025-09-25 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_execution', '0007_workorder_invoice_delivery_note'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workorder',
            name='due_in_days',
        ),
        migrations.RemoveField(
            model_name='workorder',
            name='invoice_file',
        ),
        migrations.RemoveField(
            model_name='workorder',
            name='invoice_status',
        ),
        migrations.RemoveField(
            model_name='workorder',
            name='payment_reference_number',
        ),
        migrations.RemoveField(
            model_name='workorder',
            name='received_date',
        ),
        migrations.AddField(
            model_name='deliverynoteitem',
            name='due_in_days',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deliverynoteitem',
            name='invoice_file',
            field=models.FileField(blank=True, null=True, upload_to='invoices/'),
        ),
        migrations.AddField(
            model_name='deliverynoteitem',
            name='invoice_status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('raised', 'Raised'), ('processed', 'Processed')], default='pending', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='deliverynoteitem',
            name='payment_reference_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='deliverynoteitem',
            name='received_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
