# Generated by Django 5.2.5 on 2025-09-30 06:07
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_execution', '0008_remove_workorder_due_in_days_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverynoteitem',
            name='invoice_file',
            field=models.FileField(blank=True, null=True, upload_to='invoices/'),
        ),
    ]
