# Generated by Django 5.2.4 on 2025-08-01 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_execution', '0009_workorderitem_certificate_uut_label'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workorderitem',
            name='certificate_uut_label',
        ),
    ]
