# Generated by Django 5.2.5 on 2025-09-30 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_execution', '0009_alter_deliverynoteitem_invoice_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliverynoteitem',
            name='invoice_file',
        ),
        migrations.AddField(
            model_name='deliverynoteitem',
            name='final_invoice_file',
            field=models.FileField(blank=True, null=True, upload_to='invoices/'),
        ),
    ]
