# Generated by Django 5.2.5 on 2025-09-30 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_execution', '0010_remove_deliverynoteitem_invoice_file_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deliverynoteitem',
            old_name='final_invoice_file',
            new_name='invoice_file',
        ),
    ]
