# Generated by Django 5.2.4 on 2025-08-01 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_execution', '0010_remove_workorderitem_certificate_uut_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorderitem',
            name='certificate_uut_label',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
