# Generated by Django 5.2.4 on 2025-08-01 13:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_execution', '0011_workorderitem_certificate_uut_label'),
        ('team', '0002_technician'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workorder',
            name='assigned_to',
        ),
        migrations.AddField(
            model_name='workorderitem',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_order_items', to='team.technician'),
        ),
    ]
