# Generated by Django 5.2.5 on 2025-09-30 11:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_execution', '0011_rename_final_invoice_file_deliverynoteitem_invoice_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliverynoteitem',
            name='due_in_days',
        ),
        migrations.RemoveField(
            model_name='deliverynoteitem',
            name='invoice_file',
        ),
        migrations.RemoveField(
            model_name='deliverynoteitem',
            name='invoice_status',
        ),
        migrations.RemoveField(
            model_name='deliverynoteitem',
            name='payment_reference_number',
        ),
        migrations.RemoveField(
            model_name='deliverynoteitem',
            name='received_date',
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_file', models.FileField(blank=True, null=True, upload_to='invoices/')),
                ('invoice_status', models.CharField(blank=True, choices=[('pending', 'Pending'), ('raised', 'Raised'), ('processed', 'Processed')], default='pending', max_length=20, null=True)),
                ('due_in_days', models.IntegerField(blank=True, null=True)),
                ('received_date', models.DateField(blank=True, null=True)),
                ('payment_reference_number', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('delivery_note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='job_execution.deliverynote')),
                ('delivery_note_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='job_execution.deliverynoteitem')),
            ],
        ),
    ]
