# Generated by Django 5.2.5 on 2025-09-30 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_execution', '0012_remove_deliverynoteitem_due_in_days_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='invoice_file',
            field=models.FileField(blank=True, null=True, upload_to='invoices-files/'),
        ),
    ]
