# Generated by Django 5.2.4 on 2025-08-06 05:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_execution', '0012_remove_workorder_assigned_to_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverynote',
            name='work_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_notes', to='job_execution.workorder'),
        ),
    ]
