# Generated by Django 5.2.5 on 2025-09-30 13:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_execution', '0013_alter_invoice_invoice_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='delivery_note',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='job_execution.deliverynote'),
        ),
    ]
