# Generated by Django 5.2.4 on 2025-08-06 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_execution', '0013_alter_deliverynote_work_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverynote',
            name='delivery_status',
            field=models.CharField(choices=[('Delivery Pending', 'Delivery Pending'), ('Delivered', 'Delivered')], max_length=20),
        ),
    ]
