# Generated by Django 5.2.4 on 2025-08-07 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_execution', '0014_alter_deliverynote_delivery_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorder',
            name='invoice_status',
            field=models.CharField(blank=True, choices=[('pending', 'pending'), ('Raised', 'Raised'), ('processed', 'processed')], default='pending', max_length=20, null=True),
        ),
    ]
