# Generated by Django 5.2.5 on 2025-10-05 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_execution', '0014_alter_invoice_delivery_note'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='invoice_file',
        ),
        migrations.AddField(
            model_name='invoice',
            name='final_invoice_file',
            field=models.FileField(blank=True, help_text='Final invoice file for raised status', null=True, upload_to='invoices-final/'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='processed_certificate_file',
            field=models.FileField(blank=True, help_text='Processed certificate file for processed status', null=True, upload_to='invoices-processed/'),
        ),
    ]
