# Generated by Django 5.2.4 on 2025-08-08 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_execution', '0015_workorder_invoice_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorder',
            name='due_in_days',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workorder',
            name='received_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
