# Generated by Django 5.2.5 on 2025-10-30 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_execution', '0015_remove_invoice_invoice_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='signed_invoice_file',
            field=models.FileField(blank=True, help_text='Signed invoice file for raised status', null=True, upload_to='invoices-signed/'),
        ),
    ]
