# Generated by Django 5.2.4 on 2025-08-26 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_execution', '0016_workorder_due_in_days_workorder_received_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorder',
            name='wo_type',
            field=models.CharField(blank=True, choices=[('Single', 'Single'), ('Split', 'Split')], max_length=10, null=True),
        ),
    ]
