# Generated by Django 5.2.4 on 2025-08-27 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_execution', '0017_workorder_wo_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workorder',
            name='range',
        ),
        migrations.AddField(
            model_name='workorderitem',
            name='range',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
