# Generated by Django 5.2.4 on 2025-08-28 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_execution', '0018_remove_workorder_range_workorderitem_range'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workorderitem',
            name='range',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
