# Generated by Django 5.2.4 on 2025-08-28 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_execution', '0019_alter_workorderitem_range'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workorder',
            name='serial_number',
        ),
    ]
