# Generated by Django 5.2.4 on 2025-08-28 10:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_execution', '0020_remove_workorder_serial_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryNoteItemDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(blank=True, max_length=100, null=True)),
                ('dial_size', models.CharField(blank=True, max_length=100, null=True)),
                ('case', models.CharField(blank=True, max_length=100, null=True)),
                ('connection', models.CharField(blank=True, max_length=100, null=True)),
                ('wetted_parts', models.CharField(blank=True, max_length=100, null=True)),
                ('range', models.CharField(blank=True, max_length=100, null=True)),
                ('quantity', models.PositiveIntegerField(blank=True, null=True)),
                ('delivered_quantity', models.PositiveIntegerField(blank=True, null=True)),
                ('uom', models.CharField(blank=True, max_length=100, null=True)),
                ('delivery_note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_details', to='job_execution.deliverynote')),
                ('work_order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_details', to='job_execution.workorderitem')),
            ],
        ),
    ]
