# Generated by Django 5.2.4 on 2025-08-28 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_execution', '0021_deliverynoteitemdetail'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DeliveryNoteItemDetail',
        ),
    ]
