# Generated by Django 5.2.4 on 2025-08-28 11:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0001_initial'),
        ('job_execution', '0022_delete_deliverynoteitemdetail'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryNoteItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(blank=True, max_length=100, null=True)),
                ('dial_size', models.CharField(blank=True, max_length=100, null=True)),
                ('case', models.CharField(blank=True, max_length=100, null=True)),
                ('connection', models.CharField(blank=True, max_length=100, null=True)),
                ('wetted_parts', models.CharField(blank=True, max_length=100, null=True)),
                ('range', models.CharField(blank=True, max_length=100, null=True)),
                ('quantity', models.PositiveIntegerField(blank=True, null=True)),
                ('delivered_quantity', models.PositiveIntegerField(blank=True, null=True)),
                ('uom', models.CharField(blank=True, max_length=50, null=True)),
                ('delivery_note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='job_execution.deliverynote')),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='item.item')),
            ],
        ),
    ]
