# Generated by Django 5.2.4 on 2025-08-30 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_execution', '0023_deliverynoteitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorder',
            name='application_status',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
