# Generated by Django 5.2.5 on 2025-08-30 10:24

import jsonfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_execution', '0024_workorder_application_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliverynoteitem',
            name='case',
        ),
        migrations.RemoveField(
            model_name='deliverynoteitem',
            name='connection',
        ),
        migrations.RemoveField(
            model_name='deliverynoteitem',
            name='dial_size',
        ),
        migrations.RemoveField(
            model_name='deliverynoteitem',
            name='make',
        ),
        migrations.RemoveField(
            model_name='deliverynoteitem',
            name='wetted_parts',
        ),
        migrations.AddField(
            model_name='deliverynoteitem',
            name='components',
            field=jsonfield.fields.JSONField(blank=True, null=True),
        ),
    ]
