# Generated by Django 5.2.5 on 2025-08-30 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_execution', '0027_remove_deliverynoteitem_case_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverynoteitem',
            name='components',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
