# Generated by Django 5.2.5 on 2025-09-01 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_execution', '0028_alter_deliverynoteitem_components'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliverynoteitem',
            name='components',
        ),
        migrations.AddField(
            model_name='deliverynoteitem',
            name='case',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='deliverynoteitem',
            name='connection',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='deliverynoteitem',
            name='dial_size',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='deliverynoteitem',
            name='make',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='deliverynoteitem',
            name='wetted_parts',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
