# Generated by Django 5.2.5 on 2025-09-01 06:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_execution', '0029_remove_deliverynoteitem_components_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliverynoteitem',
            name='case',
        ),
        migrations.RemoveField(
            model_name='deliverynoteitem',
            name='connection',
        ),
        migrations.RemoveField(
            model_name='deliverynoteitem',
            name='dial_size',
        ),
        migrations.RemoveField(
            model_name='deliverynoteitem',
            name='make',
        ),
        migrations.RemoveField(
            model_name='deliverynoteitem',
            name='wetted_parts',
        ),
        migrations.CreateModel(
            name='DeliveryNoteItemComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('component', models.CharField(max_length=100)),
                ('value', models.CharField(max_length=200)),
                ('delivery_note_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='job_execution.deliverynoteitem')),
            ],
        ),
    ]
