# Generated by Django 5.2.4 on 2025-07-25 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pre_job', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rfq',
            name='series_number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
