# Generated by Django 5.2.4 on 2025-07-25 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pre_job', '0004_purchaseorder_purchaseorderitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseorder',
            name='series_number',
        ),
    ]
