# Generated by Django 5.2.4 on 2025-07-30 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pre_job', '0005_remove_purchaseorder_series_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='series_number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
