# Generated by Django 5.2.4 on 2025-07-31 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pre_job', '0006_purchaseorder_series_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Collected', 'Collected'), ('Completed', 'Completed')], default='Pending', max_length=20),
        ),
    ]
