# Generated by Django 5.2.4 on 2025-07-31 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pre_job', '0007_purchaseorder_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='status',
            field=models.CharField(choices=[('Collection Pending', 'Collection Pending'), ('Collected', 'Collected'), ('Completed', 'Completed')], default='Collection Pending', max_length=20),
        ),
    ]
