# Generated by Django 5.2.4 on 2025-08-26 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pre_job', '0008_alter_purchaseorder_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rfq',
            name='rfq_status',
            field=models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Processing', 'Processing'), ('Completed', 'Completed')], max_length=20, null=True),
        ),
    ]
