# Generated by Django 5.2.4 on 2025-08-26 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pre_job', '0009_alter_rfq_rfq_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='not_approved_reason_remark',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='quotation_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('PO Created', 'PO Created'), ('Not Approved', 'Not Approved')], default='Pending', max_length=20),
        ),
    ]
