# Generated by Django 5.2.5 on 2025-09-18 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pre_job', '0010_quotation_not_approved_reason_remark_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rfq',
            name='email_sent',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
