# Generated by Django 5.2.5 on 2025-09-23 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pre_job', '0011_rfq_email_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='email_sent',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
