# Generated by Django 5.2.5 on 2025-10-06 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pre_job', '0012_quotation_email_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='vat_applicable',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='rfq',
            name='vat_applicable',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
