# Generated by Django 5.2.5 on 2025-10-08 04:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pre_job', '0013_quotation_vat_applicable_rfq_vat_applicable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rfq',
            name='email_sent',
        ),
    ]
