# Generated by Django 5.2.5 on 2025-10-30 08:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pre_job', '0014_remove_rfq_email_sent'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuotationTerms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True, default='', null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Quotation Terms & Conditions',
            },
        ),
        migrations.AddField(
            model_name='quotation',
            name='terms',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pre_job.quotationterms'),
        ),
    ]
