# Generated by Django 5.2.5 on 2025-10-30 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pre_job', '0015_quotationterms_quotation_terms'),
    ]

    operations = [
        migrations.AddField(
            model_name='rfq',
            name='email_sent',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
