# Generated by Django 5.2.5 on 2025-11-12 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pre_job', '0016_rfq_email_sent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotation',
            name='company_phone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='point_of_contact_phone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='rfq',
            name='company_phone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='rfq',
            name='point_of_contact_phone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
