# Generated by Django 5.2.5 on 2025-11-20 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pre_job', '0017_alter_quotation_company_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rfq',
            name='company_phone',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='rfq',
            name='point_of_contact_phone',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
