# Generated by Django 5.2.5 on 2025-12-10 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pre_job', '0018_alter_rfq_company_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotationterms',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
    ]
