# Generated by Django 5.2.5 on 2025-12-10 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pre_job', '0019_quotationterms_is_default'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quotationterms',
            options={'ordering': ['-updated_at'], 'verbose_name_plural': 'Quotation Terms & Conditions'},
        ),
        migrations.AddField(
            model_name='quotationterms',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
