# Generated by Django 5.2.4 on 2025-07-24 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Name of the team member', max_length=100, null=True, unique=True)),
                ('designation', models.CharField(blank=True, help_text='Designation of the team member', max_length=100, null=True)),
                ('email', models.EmailField(blank=True, help_text='email of the team member', max_length=254, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
