# Generated by Django 5.2.4 on 2025-07-30 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Technician',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Name of the technician', max_length=100, null=True, unique=True)),
                ('designation', models.CharField(blank=True, help_text='Designation of the technician', max_length=100, null=True)),
                ('email', models.EmailField(blank=True, help_text='email of the technician', max_length=254, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
